package com.aitutor.quiz;

import java.util.*;

public final class QuizBank {
    public record Q(String question, String a, String b, String c, String d, int correct, String explanation, String difficulty) {}
    private QuizBank() {}

    public static List<Q> forCourse(String title) {
        return switch (title) {
            case "HTML Mastery" -> List.of(
                    new Q("Which HTML element is used for the most important page heading?","<h1>","<h6>","<head>","<header>",0,"<h1> is the highest-level heading.","Beginner"),
                    new Q("Which attribute provides alternative text for an image?","src","alt","title","href",1,"The alt attribute provides a text alternative for an image.","Beginner"),
                    new Q("Which element semantically represents a group of navigation links?","<section>","<nav>","<aside>","<menuitem>",1,"nav is the semantic navigation landmark.","Beginner"),
                    new Q("Which element is used to create a hyperlink?","<link>","<a>","<href>","<url>",1,"The anchor element creates hyperlinks.","Beginner"),
                    new Q("Which input type is appropriate for an email address?","text","mail","email","address",2,"type=email provides email-specific input semantics and validation.","Beginner"),
                    new Q("What does the HTML lang attribute primarily help specify?","Page language","Server language","CSS version","Character encoding",0,"lang identifies the language of the document content.","Beginner"),
                    new Q("Which element is intended for a self-contained article?","<div>","<article>","<content>","<mainarticle>",1,"article represents a self-contained composition.","Intermediate"),
                    new Q("Which element should normally contain the primary unique content of a document?","<main>","<body>","<content>","<primary>",0,"main identifies the dominant content of the document.","Intermediate"),
                    new Q("Which attribute associates a label with a form control?","for","bind","control","target",0,"label for should match the control's id.","Intermediate"),
                    new Q("Which HTML element is used to define a table header cell?","<td>","<th>","<theadcell>","<header>",1,"th defines a header cell in a table.","Beginner"),
                    new Q("Which element groups introductory or navigational content for a section?","<header>","<top>","<intro>","<head>",0,"header represents introductory or navigational content.","Beginner"),
                    new Q("What is the purpose of the DOCTYPE declaration in HTML5?","Loads CSS","Declares the document type and standards mode","Creates metadata","Enables JavaScript",1,"<!DOCTYPE html> tells the browser to use HTML standards mode.","Beginner"),
                    new Q("Which element is best for an unordered list?","<ol>","<ul>","<list>","<li>",1,"ul creates an unordered list.","Beginner"),
                    new Q("Which element contains metadata such as title and linked stylesheets?","<body>","<meta>","<head>","<header>",2,"head contains document metadata and resource links.","Beginner"),
                    new Q("Which attribute makes a form control mandatory?","validate","required","mandatory","must",1,"required enables built-in required-field validation.","Intermediate"),
                    new Q("Which element embeds scalable vector graphics directly in HTML?","<vector>","<svg>","<canvas2d>","<graphic>",1,"svg embeds SVG markup.","Intermediate"),
                    new Q("Which element is commonly used for an independent image caption?","<caption>","<figcaption>","<label>","<legend>",1,"figcaption provides a caption for a figure.","Intermediate"),
                    new Q("Which element is used to embed another HTML document?","<frame>","<iframe>","<embedhtml>","<window>",1,"iframe embeds another browsing context.","Intermediate"),
                    new Q("Which attribute is used to open a link in a new browsing context?","new","target","window","open",1,"target can specify _blank for a new browsing context.","Beginner"),
                    new Q("Which semantic element represents content tangentially related to the main content?","<aside>","<extra>","<section>","<related>",0,"aside is used for tangentially related content.","Intermediate")
            );
            case "Java + Spring Boot" -> List.of(
                    new Q("Which Java feature allows one class to acquire behavior from another class?","Encapsulation","Inheritance","Overloading","Casting",1,"Inheritance models an is-a relationship between classes.","Beginner"),
                    new Q("Which collection does not allow duplicate elements?","List","Set","Queue","Map",1,"Set is designed to store unique elements.","Beginner"),
                    new Q("What is the main benefit of constructor injection in Spring?","It hides dependencies","It makes required dependencies explicit","It disables testing","It creates global variables",1,"Constructor injection makes dependencies explicit and testable.","Intermediate"),
                    new Q("Which annotation marks a Spring Boot REST controller?","@Controller","@RestController","@Service","@Endpoint",1,"@RestController combines controller semantics with response-body handling.","Beginner"),
                    new Q("Which HTTP method is normally idempotent for replacing a resource?","POST","PUT","PATCH","CONNECT",1,"PUT is defined as idempotent and is commonly used for replacement.","Intermediate"),
                    new Q("Which exception is unchecked in Java?","IOException","SQLException","NullPointerException","ClassNotFoundException",2,"NullPointerException extends RuntimeException.","Beginner"),
                    new Q("What does the final keyword on a Java variable prevent?","Reading the variable","Reassignment after initialization","Garbage collection","Method calls",1,"A final variable cannot be reassigned after initialization.","Beginner"),
                    new Q("Which interface is commonly used for sorting objects with their natural ordering?","Comparator","Comparable","Iterable","Cloneable",1,"Comparable defines natural ordering through compareTo.","Intermediate"),
                    new Q("What does @Autowired primarily do in Spring?","Creates database tables","Injects a dependency","Starts a server","Serializes JSON",1,"@Autowired requests dependency injection from the Spring container.","Beginner"),
                    new Q("Which Spring annotation is typically used for business/service-layer beans?","@Repository","@Service","@Entity","@BeanOnly",1,"@Service is the conventional stereotype for service components.","Beginner"),
                    new Q("Which annotation maps a Java class to a database table in JPA?","@TableOnly","@Entity","@Database","@Persist",1,"@Entity marks a persistent JPA entity.","Beginner"),
                    new Q("What is the purpose of @Transactional?","Enable CSS","Define a transaction boundary","Create a REST route","Compile Java",1,"It defines transactional behavior around a method/class.","Intermediate"),
                    new Q("Which Spring component is normally responsible for persistence access?","Controller","Repository","DTO","Filter",1,"Repository components abstract persistence operations.","Beginner"),
                    new Q("What status code usually indicates successful resource creation?","200","201","204","302",1,"201 Created indicates successful creation of a resource.","Beginner"),
                    new Q("Which Java collection provides average O(1) key lookup?","ArrayList","HashMap","LinkedList","TreeSet",1,"HashMap offers average constant-time key lookup under normal hashing assumptions.","Intermediate"),
                    new Q("What is method overloading?","Same method signature in child class","Same method name with different parameter lists","Replacing a private field","Creating multiple packages",1,"Overloading uses the same method name with different parameters.","Beginner"),
                    new Q("Which Spring Boot file commonly stores application configuration?","pom.java","application.properties or application.yml","Main.css","config.html",1,"Spring Boot commonly reads application.properties or application.yml.","Beginner"),
                    new Q("What is dependency inversion in a Spring application mainly supported by?","Hard-coded new calls everywhere","Dependency injection and abstractions","Global mutable state","Static-only services",1,"Dependency injection allows high-level code to depend on abstractions.","Advanced"),
                    new Q("Which layer should normally contain HTTP request/response concerns?","Repository","Controller","Entity","Database",1,"Controllers handle HTTP/API concerns.","Beginner"),
                    new Q("What is the purpose of a DTO in a REST API?","Replace the database","Control the data shape exchanged across boundaries","Start Tomcat","Encrypt the JVM",1,"DTOs define a deliberate API-facing data contract.","Intermediate")
            );
            case "DSA Fundamentals" -> List.of(
                    new Q("What is the time complexity of binary search on a sorted array?","O(n)","O(log n)","O(n log n)","O(1)",1,"Binary search halves the search interval each step.","Beginner"),
                    new Q("Which data structure follows LIFO order?","Queue","Stack","Heap","Graph",1,"A stack follows last-in, first-out order.","Beginner"),
                    new Q("Which data structure follows FIFO order?","Stack","Queue","Tree","Set",1,"A queue follows first-in, first-out order.","Beginner"),
                    new Q("What is the average time complexity of lookup in a well-designed hash table?","O(n)","O(log n)","O(1)","O(n log n)",2,"Hash-table lookup is O(1) on average with good hashing.","Beginner"),
                    new Q("Which traversal of a BST produces sorted keys?","Preorder","Inorder","Postorder","Level order",1,"Inorder traversal of a BST visits keys in sorted order.","Beginner"),
                    new Q("What is the worst-case time complexity of quicksort with poor pivot choices?","O(log n)","O(n)","O(n log n)","O(n²)",3,"Highly unbalanced partitions can produce O(n²).","Intermediate"),
                    new Q("Which technique is commonly used to detect a cycle in a linked list with O(1) extra space?","Binary search","Floyd's tortoise and hare","Merge sort","Hashing only",1,"Two pointers moving at different speeds detect a cycle.","Intermediate"),
                    new Q("What is the space complexity of an adjacency matrix for V vertices?","O(V)","O(E)","O(V²)","O(V+E)",2,"An adjacency matrix stores a V by V table.","Intermediate"),
                    new Q("Which algorithm finds shortest paths from a source in a graph with non-negative edge weights?","DFS","Dijkstra's algorithm","Kruskal's algorithm","Binary search",1,"Dijkstra's algorithm assumes non-negative edge weights.","Intermediate"),
                    new Q("Which sorting algorithm has O(n log n) worst-case complexity and is stable in its standard form?","Selection sort","Merge sort","Quick sort","Bubble sort",1,"Merge sort is stable and has O(n log n) worst-case time.","Intermediate"),
                    new Q("What is the recurrence pattern behind merge sort?","T(n)=T(n-1)+1","T(n)=2T(n/2)+O(n)","T(n)=T(n/2)+O(1)","T(n)=nT(n-1)",1,"Merge sort splits into two halves and merges in linear time.","Intermediate"),
                    new Q("Which data structure is most appropriate for BFS?","Stack","Queue","Heap","HashSet",1,"BFS processes vertices level by level using a queue.","Beginner"),
                    new Q("Which data structure is typically used for DFS iteratively?","Queue","Stack","Heap","Priority queue",1,"An explicit stack can implement iterative DFS.","Beginner"),
                    new Q("What does Big-O describe?","Exact CPU time on one machine","Asymptotic growth of resource usage","Only memory addresses","Compiler version",1,"Big-O describes asymptotic growth as input size increases.","Beginner"),
                    new Q("What is the worst-case time complexity of linear search?","O(1)","O(log n)","O(n)","O(n log n)",2,"A linear search may inspect every element.","Beginner"),
                    new Q("Which approach stores solutions to overlapping subproblems?","Greedy only","Dynamic programming","Binary search","Randomization only",1,"Dynamic programming reuses results of overlapping subproblems.","Intermediate"),
                    new Q("Which property is required for binary search?","Unsorted data","An ordered search space","A linked list only","Unique values only",1,"Binary search needs an ordered search space.","Beginner"),
                    new Q("What is the main goal of a two-pointer technique?","Always use recursion","Reduce repeated scanning by coordinating indices","Sort every input","Use a database",1,"Two pointers often reduce a nested scan to a linear pass.","Intermediate"),
                    new Q("Which heap is commonly used to implement a min-priority queue?","Max heap","Min heap","Binary search tree only","Trie",1,"A min-heap exposes the smallest key efficiently.","Intermediate"),
                    new Q("What is the typical time complexity of inserting at the head of a linked list?","O(1)","O(log n)","O(n)","O(n log n)",0,"With a head pointer, insertion at the front is constant time.","Beginner")
            );
            case "Python Programming" -> List.of(
                    new Q("What is the output type of range(5)?","list","range object","tuple","set",1,"range returns a range object.","Beginner"),
                    new Q("Which Python collection is mutable and ordered?","tuple","list","frozenset","str",1,"Lists are mutable ordered sequences.","Beginner"),
                    new Q("What does == compare in Python?","Object identity only","Equality of values/objects","Memory addresses only","Types only",1,"== performs equality comparison.","Beginner"),
                    new Q("Which keyword defines a function?","func","def","function","lambda",1,"def defines a named function.","Beginner"),
                    new Q("What is a dictionary lookup generally based on?","Index position","Hashable key","Sorted array only","Line number",1,"Dictionaries use hashable keys for efficient lookup.","Beginner"),
                    new Q("Which statement handles exceptions?","try/except","if/error","catch/finally","handle/error",0,"Python uses try/except for exception handling.","Beginner"),
                    new Q("What does list.append(x) do?","Removes x","Adds x to the end","Sorts the list","Copies the list",1,"append adds one element at the end.","Beginner"),
                    new Q("What is a Python generator typically created with?","yield","generate","returnall","nextdef",0,"yield produces values lazily from a generator.","Intermediate"),
                    new Q("Which is immutable?","list","set","tuple","dict",2,"Tuples are immutable sequences.","Beginner"),
                    new Q("What does len([1,2,3]) return?","2","3","4","Error",1,"The list contains three elements.","Beginner"),
                    new Q("Which construct is used for a compact list transformation?","List comprehension","List compiler","Map block","Loop literal",0,"List comprehensions create lists from iterable expressions compactly.","Beginner"),
                    new Q("What does self refer to in an instance method?","The class definition","The current instance","The parent module","The interpreter",1,"self refers to the current instance by convention.","Beginner"),
                    new Q("Which module is commonly used for JSON encoding/decoding?","json","picklejson","serialize","httpjson",0,"The standard json module handles JSON data.","Beginner"),
                    new Q("What is the purpose of virtual environments?","Increase CPU speed","Isolate project dependencies","Compile Python to Java","Replace pip",1,"Virtual environments isolate package dependencies per project.","Intermediate"),
                    new Q("Which operator performs integer floor division?","/","//","%","**",1,"// performs floor division.","Beginner"),
                    new Q("What does *args collect in a function?","Keyword arguments","Positional arguments","Imports","Classes",1,"*args collects extra positional arguments.","Intermediate"),
                    new Q("What does **kwargs collect?","Positional arguments","Keyword arguments","Exceptions","Modules",1,"**kwargs collects extra keyword arguments.","Intermediate"),
                    new Q("Which data type stores unique elements without guaranteed order?","list","set","tuple","str",1,"set stores unique elements.","Beginner"),
                    new Q("What is the usual time complexity of membership in a set on average?","O(1)","O(log n)","O(n²)","O(n log n)",0,"Hash-based set membership is O(1) on average.","Intermediate"),
                    new Q("Which library is commonly used for tabular data analysis?","NumPy only","pandas","pytest","Flask",1,"pandas provides DataFrame-based tabular data tools.","Beginner")
            );
            case "SQL & Database Mastery" -> List.of(
                    new Q("Which clause filters rows before grouping?","HAVING","WHERE","ORDER BY","GROUP BY",1,"WHERE filters rows before grouping.","Beginner"),
                    new Q("Which clause filters groups after GROUP BY?","WHERE","HAVING","FILTER BY","ORDER BY",1,"HAVING filters grouped results.","Beginner"),
                    new Q("Which JOIN returns matching rows from both tables?","LEFT JOIN","INNER JOIN","CROSS JOIN","FULL JOIN",1,"INNER JOIN returns rows satisfying the join condition.","Beginner"),
                    new Q("Which SQL command removes rows while keeping the table structure?","DROP","DELETE","ALTER","TRUNCATE DATABASE",1,"DELETE removes rows while preserving the table definition.","Beginner"),
                    new Q("What is a primary key required to be?","Nullable and duplicated","Unique and non-null","Text only","Foreign",1,"A primary key uniquely identifies rows and cannot be null.","Beginner"),
                    new Q("Which index structure is commonly used by relational databases for range queries?","B-tree","Stack","Queue","Trie only",0,"B-tree family indexes support ordered/range access efficiently.","Intermediate"),
                    new Q("What does normalization primarily reduce?","CPU cores","Redundant data and update anomalies","Network bandwidth only","Query syntax",1,"Normalization reduces redundancy and anomalies.","Intermediate"),
                    new Q("Which command changes table structure?","ALTER TABLE","UPDATE TABLE ONLY","MODIFY ROW","CHANGE DATABASE",0,"ALTER TABLE changes table definitions.","Beginner"),
                    new Q("What does COUNT(*) count?","Only non-null columns","Rows","Only distinct rows","Tables",1,"COUNT(*) counts rows in the result set.","Beginner"),
                    new Q("Which constraint enforces referential integrity?","CHECK","FOREIGN KEY","DEFAULT","UNIQUE",1,"Foreign keys enforce references between tables.","Beginner"),
                    new Q("What does DISTINCT do in SELECT?","Sorts rows","Removes duplicate result rows","Groups rows","Deletes data",1,"DISTINCT removes duplicate result rows.","Beginner"),
                    new Q("Which isolation problem involves reading uncommitted data?","Dirty read","Deadlock","Lost schema","Phantom write",0,"A dirty read observes another transaction's uncommitted changes.","Advanced"),
                    new Q("What does COMMIT do?","Undoes a transaction","Makes transaction changes durable","Drops a table","Creates an index",1,"COMMIT finalizes the transaction.","Intermediate"),
                    new Q("What does ROLLBACK do?","Persists all changes","Undoes uncommitted transaction changes","Creates a view","Sorts data",1,"ROLLBACK reverts uncommitted changes.","Intermediate"),
                    new Q("Which SQL operator checks whether a value lies within an inclusive range?","BETWEEN","RANGEONLY","INBETWEEN","WITHIN",0,"BETWEEN includes both endpoints in standard SQL semantics.","Beginner"),
                    new Q("Which normal form removes partial dependency on part of a composite key?","1NF","2NF","3NF","BCNF",1,"Second normal form removes partial dependencies.","Advanced"),
                    new Q("Which query retrieves departments having more than 5 employees?","WHERE COUNT(*) > 5","HAVING COUNT(*) > 5","GROUP BY COUNT(*) > 5","ORDER BY COUNT(*) > 5",1,"Aggregate filters belong in HAVING after grouping.","Intermediate"),
                    new Q("What is a view?","A physical CPU cache","A stored query presented as a virtual table","A backup only","An index",1,"A view is a virtual table based on a query.","Intermediate"),
                    new Q("What is the purpose of EXPLAIN in many SQL systems?","Delete slow queries","Inspect a query execution plan","Encrypt the query","Create users",1,"EXPLAIN helps analyze how the database plans to execute a query.","Advanced"),
                    new Q("Which operation combines rows from two queries and removes duplicates by default?","UNION","JOIN","MERGE TABLE","APPEND ONLY",0,"UNION combines compatible result sets and removes duplicates by default.","Intermediate")
            );
            case "Computer Networks" -> List.of(
                    new Q("Which layer of the OSI model provides end-to-end transport?","Network","Transport","Session","Data Link",1,"The transport layer provides end-to-end transport services.","Beginner"),
                    new Q("Which protocol maps a domain name to an IP address?","HTTP","DNS","FTP","ARP",1,"DNS resolves domain names.","Beginner"),
                    new Q("Which protocol provides reliable byte-stream delivery?","UDP","TCP","IP","ICMP",1,"TCP provides reliable ordered byte-stream delivery.","Beginner"),
                    new Q("Which protocol is connectionless and generally lower overhead than TCP?","TCP","UDP","TLS","SSH",1,"UDP is connectionless and has less transport overhead.","Beginner"),
                    new Q("What is the default port for HTTPS?","80","21","443","53",2,"HTTPS commonly uses TCP port 443.","Beginner"),
                    new Q("What does ARP resolve on a local network?","Domain to IP","IP to MAC","MAC to domain","Port to process",1,"ARP resolves an IPv4 address to a link-layer MAC address on a local network.","Intermediate"),
                    new Q("Which device primarily forwards packets between networks?","Switch","Router","Hub","Repeater",1,"Routers forward packets between networks.","Beginner"),
                    new Q("What is the purpose of a subnet mask?","Encrypt traffic","Separate network and host portions of an IP address","Assign DNS names","Open ports",1,"A subnet mask identifies network versus host bits.","Beginner"),
                    new Q("Which HTTP method is commonly safe and idempotent for retrieving a resource?","GET","POST","CONNECT","PATCH",0,"GET is safe and idempotent when used normally for retrieval.","Beginner"),
                    new Q("Which protocol is commonly used to securely administer a remote Linux server?","FTP","SSH","SMTP","DHCP",1,"SSH provides secure remote shell access.","Beginner"),
                    new Q("Which protocol automatically provides IP configuration to hosts?","DNS","DHCP","ARP","SNMP",1,"DHCP can assign IP configuration dynamically.","Beginner"),
                    new Q("What is packet switching?","Sending an entire network over one wire","Splitting data into packets forwarded through a network","Encrypting every packet with HTTP","Replacing routers",1,"Packet switching divides data into packets that are forwarded independently.","Intermediate"),
                    new Q("Which layer is responsible for routing in the OSI model?","Physical","Data Link","Network","Presentation",2,"The network layer handles logical addressing and routing.","Beginner"),
                    new Q("What does NAT commonly do?","Encrypt DNS","Translate private and public addresses","Replace TCP","Compress packets",1,"NAT translates address spaces, commonly private to public.","Intermediate"),
                    new Q("Which DNS record maps a name to an IPv4 address?","MX","A","CNAME","TXT",1,"An A record maps a hostname to an IPv4 address.","Beginner"),
                    new Q("What is latency?","Amount of stored data","Time taken for data to travel/receive a response","Number of users","Bandwidth limit",1,"Latency measures delay in communication.","Beginner"),
                    new Q("Which mechanism helps TCP avoid overwhelming a receiver?","Flow control","DNS","ARP","NAT",0,"TCP flow control uses the receive window to regulate sender rate.","Intermediate"),
                    new Q("What is the purpose of TLS in HTTPS?","Route packets","Provide encryption and authentication for the connection","Assign IP addresses","Compress HTML",1,"TLS protects HTTP traffic with encryption and authentication.","Intermediate"),
                    new Q("Which address is used for delivery within a local Ethernet segment?","MAC address","URL","Port only","DNS name",0,"Ethernet frames use MAC addresses for local delivery.","Beginner"),
                    new Q("What is a three-way handshake associated with?","UDP","TCP connection establishment","DNS caching","HTTP compression",1,"TCP uses SYN, SYN-ACK and ACK to establish a connection.","Intermediate")
            );
            case "Operating Systems" -> List.of(
                    new Q("Which component manages hardware resources and provides core services to programs?","Compiler","Kernel","Browser","Shell script",1,"The kernel manages CPU, memory, devices and other core resources.","Beginner"),
                    new Q("Which scheduling algorithm can cause starvation if priorities are not managed?","FCFS","Priority scheduling","Round robin only","FIFO disk scheduling",1,"Low-priority processes can starve under priority scheduling.","Intermediate"),
                    new Q("What is a process?","A source-code comment","A program in execution","A CPU instruction only","A file extension",1,"A process is a running instance of a program.","Beginner"),
                    new Q("What is a thread?","A complete operating system","A unit of execution within a process","A disk partition","A network packet",1,"Threads are execution units within a process.","Beginner"),
                    new Q("Which scheduling algorithm uses a time quantum?","Round Robin","FCFS","SJF only","Priority only",0,"Round Robin allocates CPU time slices.","Beginner"),
                    new Q("What is virtual memory?","Extra physical CPU","An abstraction that uses storage to extend apparent memory","A faster cache only","A network drive",1,"Virtual memory uses address translation and secondary storage to provide a larger address space.","Intermediate"),
                    new Q("Which condition is one of the Coffman deadlock conditions?","Infinite bandwidth","Mutual exclusion","No processes","Single CPU only",1,"Mutual exclusion is one of the four necessary deadlock conditions.","Intermediate"),
                    new Q("Which page replacement algorithm can suffer from Belady's anomaly?","FIFO","LRU always","Optimal always","MRU always",0,"FIFO can exhibit Belady's anomaly.","Advanced"),
                    new Q("What is a context switch?","Changing source code","Switching CPU execution from one process/thread to another","Restarting a database","Changing an IP address",1,"The OS saves one execution context and restores another.","Beginner"),
                    new Q("What is a system call?","A Java method","An interface through which a program requests OS services","A hardware interrupt only","A database query",1,"System calls provide controlled access to OS services.","Intermediate"),
                    new Q("Which memory is closest to the CPU among these?","Disk","RAM","Cache","Network storage",2,"CPU cache is closer and faster than RAM and storage.","Beginner"),
                    new Q("What does a semaphore help coordinate?","HTML layout","Concurrent access to shared resources","DNS resolution","Disk formatting",1,"Semaphores coordinate concurrent access and signaling.","Intermediate"),
                    new Q("Which filesystem property helps map names to file metadata?","Inode","Socket","Thread","Register",0,"Unix-like filesystems use inodes for file metadata.","Intermediate"),
                    new Q("What is thrashing?","CPU overclocking","Excessive paging that leaves little useful CPU work","Disk formatting","Network congestion",1,"Thrashing occurs when excessive paging dominates execution.","Intermediate"),
                    new Q("Which page replacement policy uses recent access history?","LRU","FIFO","Random only","FCFS",0,"LRU replaces the page least recently used.","Intermediate"),
                    new Q("What is a race condition?","A faster CPU","Incorrect behavior caused by timing-dependent concurrent access","A memory leak only","A disk failure",1,"A race occurs when concurrent operations access shared state without proper synchronization.","Intermediate"),
                    new Q("Which technique avoids external fragmentation for allocated pages?","Paging","Only segmentation","Manual compaction always","Single partition",0,"Paging uses fixed-size pages/frames and avoids external fragmentation.","Intermediate"),
                    new Q("What is starvation?","All processes finish","A process waits indefinitely for resources/CPU","Memory becomes read-only","A disk becomes empty",1,"Starvation means a process may wait indefinitely for service.","Beginner"),
                    new Q("Which state means a process is waiting for an event such as I/O?","Running","Blocked/Waiting","New only","Terminated",1,"A blocked process waits for an event or resource.","Beginner"),
                    new Q("What does mutual exclusion guarantee?","All threads run together","At most one thread enters a critical section at a time","No thread can run","Every process gets equal CPU",1,"Mutual exclusion protects critical sections from simultaneous entry.","Beginner")
            );
            case "System Design Fundamentals" -> List.of(
                    new Q("What is horizontal scaling?","Adding more CPU to one server","Adding more server instances","Removing replicas","Increasing log size",1,"Horizontal scaling adds instances.","Beginner"),
                    new Q("What is a load balancer used for?","Store passwords","Distribute traffic across servers","Compile code","Replace databases",1,"Load balancers distribute requests among backend instances.","Beginner"),
                    new Q("What is caching primarily used to improve?","Code formatting","Latency and backend load for repeated data","Database schema correctness","Password entropy",1,"Caches reduce repeated expensive work and improve response time.","Beginner"),
                    new Q("What is a database index mainly used for?","Encrypt rows","Speed up selected queries","Increase normalization automatically","Replace backups",1,"Indexes accelerate lookup at the cost of storage/write overhead.","Beginner"),
                    new Q("What does eventual consistency mean?","All replicas are instantly identical","Replicas may temporarily differ but converge","Data is never consistent","Only one server stores data",1,"Eventual consistency allows temporary divergence with eventual convergence.","Intermediate"),
                    new Q("Why is a message queue useful?","It removes all failures","It decouples producers and consumers","It replaces authentication","It guarantees zero latency",1,"Queues decouple components and absorb asynchronous workloads.","Intermediate"),
                    new Q("What is a CDN mainly used for?","Database transactions","Serving content closer to users","Generating SQL","Managing passwords",1,"CDNs cache and serve content from geographically distributed edges.","Beginner"),
                    new Q("What does idempotency mean for an API operation?","It always succeeds","Repeating the same request has the same intended effect as one request","It is always faster","It cannot be retried",1,"Idempotent operations can be safely repeated with the same intended state effect.","Intermediate"),
                    new Q("What is a common reason to partition/shard a database?","Reduce code readability","Scale data and traffic beyond one database node","Avoid all indexes","Remove backups",1,"Sharding distributes data/load across nodes.","Advanced"),
                    new Q("What is the CAP theorem concerned with during a network partition?","CPU, API, process","Consistency, availability and partition tolerance","Caching, auth, persistence","Code, algorithms, performance",1,"CAP describes trade-offs among consistency, availability and partition tolerance.","Advanced"),
                    new Q("What is a read replica commonly used for?","Handling read traffic and offloading the primary","Replacing authentication","Writing all transactions","Compiling queries",0,"Read replicas can serve read workloads and reduce primary load.","Intermediate"),
                    new Q("What is a circuit breaker pattern designed to prevent?","SQL syntax errors","Repeated calls to an unhealthy dependency","User registration","Database normalization",1,"Circuit breakers stop cascading failures from repeated failing calls.","Advanced"),
                    new Q("What is rate limiting used for?","Increase duplicate traffic","Control request volume","Remove caching","Change schemas",1,"Rate limiting controls how many requests a client can make.","Beginner"),
                    new Q("What does stateless service design mean?","No database exists","Each request contains enough context so any instance can handle it","Only one server is allowed","State is stored in CPU registers",1,"Stateless services avoid relying on local per-user session state.","Intermediate"),
                    new Q("What is a cache invalidation strategy concerned with?","When cached data should be removed or refreshed","How to compile Java","How to route DNS","How to create users",0,"Invalidation determines when cached entries stop being trusted.","Intermediate"),
                    new Q("Why use database connection pooling?","Open a new connection for every query","Reuse established connections efficiently","Avoid all transactions","Disable SQL",1,"Pooling reuses connections and reduces connection setup overhead.","Intermediate"),
                    new Q("What is an SLO?","A source-level object","A target for a service reliability/quality metric","A database table","A load balancer algorithm",1,"An SLO defines a target level for a service metric.","Advanced"),
                    new Q("What does backpressure help with?","Handling faster producers than consumers","Encrypting traffic","Normalizing tables","Creating indexes",0,"Backpressure prevents consumers from being overwhelmed by producers.","Advanced"),
                    new Q("What is a reverse proxy?","A client-side database","A server-side intermediary that forwards client requests to backend services","A CPU scheduler","A compiler",1,"Reverse proxies sit in front of backend services and forward requests.","Intermediate"),
                    new Q("What is observability commonly built from?","Only source code","Logs, metrics and traces","Only backups","Only DNS",1,"Logs, metrics and traces provide complementary operational visibility.","Intermediate")
            );
            case "Git & GitHub" -> List.of(
                    new Q("Which command creates a new Git repository?","git start","git init","git new","git repo",1,"git init initializes a repository.","Beginner"),
                    new Q("Which command stages changes?","git stage-all","git add","git commit","git push",1,"git add stages changes for the next commit.","Beginner"),
                    new Q("Which command records staged changes in history?","git save","git commit","git record","git snapshot",1,"git commit creates a commit from staged changes.","Beginner"),
                    new Q("Which command sends local commits to a remote repository?","git upload","git push","git send","git publish",1,"git push updates a remote branch with local commits.","Beginner"),
                    new Q("Which command downloads remote commits and integrates them into the current branch by default?","git fetch","git pull","git clone","git sync",1,"git pull fetches and integrates changes.","Beginner"),
                    new Q("Which command creates a new branch?","git branch feature","git make feature","git new-branch feature","git fork feature",0,"git branch feature creates a branch named feature.","Beginner"),
                    new Q("What is a merge conflict?","A failed login","Git cannot automatically reconcile competing changes","A deleted repository","A network timeout only",1,"Conflicts occur when Git cannot automatically combine changes.","Beginner"),
                    new Q("What is a pull request mainly used for?","Local compilation","Proposing and reviewing changes before merging","Deleting branches","Creating passwords",1,"Pull requests support review and controlled integration.","Beginner"),
                    new Q("What does git clone do?","Deletes a repository","Copies a remote repository locally","Creates a commit","Stages files",1,"clone creates a local copy of a repository.","Beginner"),
                    new Q("What does git status show?","CPU usage","Working tree and staging state","Remote server uptime","Only commit messages",1,"git status reports changed/staged/untracked files and branch state.","Beginner"),
                    new Q("What is .gitignore used for?","Ignoring commits","Specifying files Git should not track","Deleting remote branches","Encrypting files",1,".gitignore defines patterns for untracked files Git should ignore.","Beginner"),
                    new Q("What does git diff commonly show?","Database rows","Differences between file states","Remote users","Branch permissions",1,"git diff shows changes between states.","Beginner"),
                    new Q("What is rebase primarily used for?","Delete all history","Replay commits onto another base","Create a database","Upload binaries",1,"Rebase rewrites commit ancestry by replaying commits on a new base.","Intermediate"),
                    new Q("Why should force-push be used carefully on shared branches?","It changes commit history","It increases CPU speed","It disables Git","It creates tags",0,"Force push can overwrite remote history.","Intermediate"),
                    new Q("What is a tag commonly used for?","Temporary memory","Marking a specific commit such as a release","Deleting commits","Creating issues",1,"Tags can identify release points in history.","Beginner"),
                    new Q("What is HEAD in Git?","Remote server","Current checked-out reference/commit context","A password","A branch name only",1,"HEAD identifies the current checked-out commit/reference.","Intermediate"),
                    new Q("Which command can create a commit that undoes a previous commit without rewriting shared history?","git erase","git revert","git destroy","git reset-hard",1,"git revert creates a new inverse commit.","Intermediate"),
                    new Q("What is a fork on GitHub?","A local branch","A server-side copy of a repository under another account/org","A commit","A release tag",1,"A fork is an independent GitHub repository copy linked to the upstream project.","Beginner"),
                    new Q("Which branch is often protected from direct pushes in team workflows?","main","tmp","scratch","local",0,"main is commonly protected in collaborative repositories.","Beginner"),
                    new Q("What is semantic commit history useful for?","Only colors","Understanding changes and maintaining traceability","Avoiding branches","Replacing tests",1,"Clear commits make changes easier to review and trace.","Intermediate")
            );
            case "JavaScript & React" -> List.of(
                    new Q("Which keyword declares a block-scoped variable that can be reassigned?","var","let","const","static",1,"let is block-scoped and can be reassigned.","Beginner"),
                    new Q("Which keyword declares a binding that cannot be reassigned?","let","const","var","fixed",1,"const prevents reassignment of the binding.","Beginner"),
                    new Q("What does === check in JavaScript?","Only value after coercion","Strict equality of value and type","Only object identity","Only strings",1,"=== performs strict equality without type coercion.","Beginner"),
                    new Q("What is the purpose of React components?","Manage databases","Build reusable UI pieces","Compile CSS","Create server sockets",1,"Components encapsulate reusable UI and behavior.","Beginner"),
                    new Q("Which hook stores local component state?","useRoute","useState","useClass","useStoreOnly",1,"useState adds state to a function component.","Beginner"),
                    new Q("Which hook is commonly used for side effects?","useEffect","useSide","useAsyncOnly","useEvent",0,"useEffect runs side-effect logic after render according to dependencies.","Beginner"),
                    new Q("What is a React key used for in lists?","Encryption","Helping React identify list items across renders","Styling","Routing only",1,"Keys help React reconcile list items.","Beginner"),
                    new Q("What does JSX allow?","SQL inside CSS","JavaScript syntax with XML-like UI markup","Java bytecode","HTML only",1,"JSX is a syntax extension commonly used to describe React UI.","Beginner"),
                    new Q("What is a controlled input in React?","An input controlled by CSS","An input whose value is driven by React state","A disabled input","A server-only input",1,"Controlled inputs derive their value from component state.","Intermediate"),
                    new Q("What does lifting state up mean?","Moving state into CSS","Moving shared state to a common ancestor","Deleting state","Saving state to SQL",1,"Shared state is placed in the nearest common owner.","Intermediate"),
                    new Q("What does the virtual DOM concept help React do?","Store SQL","Efficiently reconcile UI changes","Replace JavaScript","Compile images",1,"React uses a virtual representation to reconcile UI updates.","Intermediate"),
                    new Q("Which method transforms an array into another array?","forEach","map","reduceOnly","filterOnly",1,"map returns a new array of transformed elements.","Beginner"),
                    new Q("Which method selects elements matching a condition?","map","filter","join","push",1,"filter returns elements for which the predicate is truthy.","Beginner"),
                    new Q("What is event bubbling?","An event being removed","An event propagating from a target toward ancestors","A CSS animation","A network retry",1,"Events can propagate upward through the DOM.","Intermediate"),
                    new Q("Why should expensive derived calculations sometimes be memoized?","To guarantee correctness","To avoid unnecessary recomputation","To replace state","To remove renders entirely",1,"Memoization can avoid repeating expensive calculations when inputs are unchanged.","Intermediate"),
                    new Q("What is React Router commonly used for?","Database queries","Client-side navigation and route rendering","Image compression","API authentication only",1,"React Router manages client-side routes.","Beginner"),
                    new Q("What does a dependency array in useEffect influence?","CSS specificity","When the effect re-runs","Database indexing","Component names",1,"Dependencies determine when React re-runs the effect.","Intermediate"),
                    new Q("Why should state updates avoid direct mutation?","Mutation is always slower","React relies on predictable state changes and references","Mutation crashes JavaScript","It disables JSX",1,"Immutable updates make state changes predictable and detectable.","Intermediate"),
                    new Q("What is prop drilling?","Compiling props","Passing props through intermediate components to reach a deep child","Deleting props","Using CSS props",1,"Prop drilling passes data through components that do not otherwise need it.","Intermediate"),
                    new Q("Which React pattern is useful when many unrelated components need shared state?","Global/shared state management","Only local variables","CSS inheritance","HTML comments",0,"Shared state solutions can coordinate data across distant components.","Advanced")
            );
            case "Spring Security & REST APIs" -> List.of(
                    new Q("Which HTTP status code usually means authentication is required or invalid?","200","401","403","404",1,"401 indicates missing/invalid authentication credentials.","Beginner"),
                    new Q("Which status code means the server understood the request but refuses authorization?","201","204","403","409",2,"403 indicates insufficient permission for an authenticated request.","Beginner"),
                    new Q("What is JWT commonly used for?","Database indexing","Representing signed claims for stateless authentication","CSS styling","File compression",1,"JWTs can carry signed authentication/authorization claims.","Intermediate"),
                    new Q("Where should a server-side JWT signing secret be stored?","Frontend source code","Secure server-side configuration/secret storage","URL query string","Public README",1,"Signing secrets must not be exposed to clients.","Beginner"),
                    new Q("Which Spring annotation enables method-level authorization rules in modern Spring Security?","@EnableMethodSecurity","@EnableSQL","@SecureRESTOnly","@MethodAuthOnly",0,"@EnableMethodSecurity enables method authorization support.","Intermediate"),
                    new Q("What is the purpose of a SecurityFilterChain?","Create database tables","Configure HTTP security filters and authorization","Generate React pages","Compile Java",1,"It configures Spring Security's web filter chain.","Intermediate"),
                    new Q("What is CORS?","Database replication","A browser security mechanism governing cross-origin requests","A password hash","A Java compiler",1,"CORS controls which cross-origin browser requests are permitted.","Beginner"),
                    new Q("Why should passwords be hashed rather than encrypted for normal authentication storage?","Hashes are reversible","Passwords should not need to be recovered in plaintext","Encryption is always slower","Hashing exposes passwords",1,"Password verification should use one-way password hashing.","Beginner"),
                    new Q("Which HTTP method is commonly used to create a resource?","GET","POST","DELETE","HEAD",1,"POST is commonly used for resource creation.","Beginner"),
                    new Q("Which HTTP method is commonly used to delete a resource?","GET","POST","DELETE","OPTIONS",2,"DELETE requests resource deletion.","Beginner"),
                    new Q("What should an API return for malformed request validation?","Always 200","A suitable 4xx validation response","500 always","302",1,"Client validation errors generally belong to the 4xx range.","Intermediate"),
                    new Q("Why use DTOs in a secured API?","They disable authentication","They control exposed data and decouple API contracts from entities","They replace TLS","They remove validation",1,"DTOs prevent accidental exposure and stabilize API contracts.","Intermediate"),
                    new Q("What is CSRF protection primarily concerned with?","SQL indexes","Forged state-changing browser requests","JWT signing only","DNS spoofing only",1,"CSRF protects against unauthorized state-changing requests made from a user's browser context.","Advanced"),
                    new Q("Which header commonly carries a bearer access token?","Content-Type","Authorization","Accept-Language","X-Database",1,"Bearer tokens are commonly sent in the Authorization header.","Beginner"),
                    new Q("What does HTTPS add to HTTP?","Database joins","TLS-based encryption and authentication","A larger JSON schema","A new SQL dialect",1,"HTTPS uses TLS to secure HTTP communication.","Beginner"),
                    new Q("What is role-based authorization?","Assigning CSS roles","Granting permissions based on roles","Using only passwords","Disabling endpoints",1,"Roles group permissions used to authorize actions.","Beginner"),
                    new Q("Why should sensitive fields be excluded from API responses?","To reduce Java syntax","To avoid leaking secrets or private data","To disable caching","To increase latency",1,"Responses should expose only data the client needs and is allowed to see.","Intermediate"),
                    new Q("What is the purpose of rate limiting on an authenticated API?","Make every request slower","Reduce abuse and protect service capacity","Replace authentication","Disable users",1,"Rate limiting limits request volume and protects capacity.","Intermediate"),
                    new Q("What is least privilege?","Give every user admin access","Grant only the permissions required for a task","Disable all permissions","Use one shared password",1,"Least privilege minimizes unnecessary access.","Beginner"),
                    new Q("Why should authorization be enforced on the backend even if the UI hides buttons?","UI controls are not security boundaries","It improves CSS","It removes routing","It avoids JSON",0,"Clients can be manipulated; backend authorization is authoritative.","Intermediate")
            );
            case "Cloud & DevOps Fundamentals" -> List.of(
                    new Q("What problem does CI primarily address?","Manual typing","Automatically building and testing changes","Database normalization","UI design",1,"Continuous integration automates build/test validation for changes.","Beginner"),
                    new Q("What does CD commonly stand for in deployment workflows?","Code deletion","Continuous delivery/deployment","CPU distribution","Container deletion",1,"CD commonly refers to continuous delivery or continuous deployment.","Beginner"),
                    new Q("What is a container?","A virtual machine with its own kernel","An isolated process environment sharing the host kernel","A database table","A Git branch",1,"Containers isolate processes while sharing the host kernel.","Beginner"),
                    new Q("Which file commonly defines a Docker image build?","Dockerfile","Container.yml only","Image.java","docker.sql",0,"Dockerfile contains image build instructions.","Beginner"),
                    new Q("What is Kubernetes primarily used for?","Editing source code","Orchestrating containerized workloads","Creating SQL indexes","Designing websites",1,"Kubernetes automates deployment and management of containers.","Beginner"),
                    new Q("What is infrastructure as code?","Writing hardware manually","Defining infrastructure declaratively in version-controlled code","Compiling kernels","Drawing network diagrams",1,"IaC manages infrastructure through code/configuration.","Intermediate"),
                    new Q("What is horizontal pod autoscaling in Kubernetes used for?","Changing source code","Adjusting pod replicas based on metrics","Creating databases","Rotating SSH keys",1,"HPA changes replica counts based on observed metrics.","Intermediate"),
                    new Q("Which metric is commonly associated with service latency?","Request duration","Source lines","Git branches","Disk filename",0,"Request duration is a direct latency metric.","Beginner"),
                    new Q("What is a health check used for?","Changing passwords","Determining whether a service is able to receive traffic","Writing Java code","Creating commits",1,"Health checks allow systems to detect unhealthy instances.","Beginner"),
                    new Q("What is a rolling deployment?","Deploying all servers simultaneously","Gradually replacing instances with a new version","Never deploying","Deleting old code first",1,"Rolling deployments replace instances incrementally.","Intermediate"),
                    new Q("What is a blue-green deployment?","Two databases only","Two production environments used to switch traffic between versions","A DNS record type","A Docker image color",1,"Blue-green keeps two environments and switches traffic between them.","Intermediate"),
                    new Q("What is a secret manager used for?","Store CSS","Securely store and retrieve sensitive configuration","Run SQL joins","Create UI pages",1,"Secret managers protect credentials and other sensitive values.","Beginner"),
                    new Q("What is observability?","Only server logs","Ability to understand system behavior using telemetry","Only CPU scaling","A programming language",1,"Observability uses telemetry such as logs, metrics and traces.","Intermediate"),
                    new Q("What does immutable infrastructure mean?","Servers never restart","Replace instances rather than modifying them in place","No backups","No containers",1,"Immutable infrastructure favors replacement over manual mutation.","Advanced"),
                    new Q("What is a reverse proxy commonly used for in cloud deployments?","Store passwords","Route requests to backend services and provide edge concerns","Compile containers","Replace Git",1,"Reverse proxies route traffic and can handle TLS, caching and more.","Intermediate"),
                    new Q("Why use a CDN for static assets?","To execute SQL","To serve content closer to users","To create Git commits","To hash passwords",1,"CDNs reduce distance and latency for cached content.","Beginner"),
                    new Q("What does a rolling restart try to preserve?","Zero source code","Service availability while instances restart incrementally","No network traffic","No logs",1,"Rolling restarts limit simultaneous disruption.","Intermediate"),
                    new Q("What is a deployment rollback?","A new database schema only","Returning to a previously known-good version","Deleting all users","Changing DNS names only",1,"Rollback restores a prior version after a bad release.","Beginner"),
                    new Q("What is horizontal pod autoscaling based on?","Only Git history","Configured metrics and utilization targets","HTML tags","SQL syntax",1,"HPA evaluates configured metrics and target utilization.","Intermediate"),
                    new Q("Why are automated tests important in CI/CD?","They guarantee zero bugs","They catch regressions before changes reach later environments","They replace monitoring","They remove code review",1,"Automated tests provide repeatable regression checks.","Beginner")
            );
            case "Aptitude & Placement Prep" -> List.of(
                    new Q("A train 120 m long crosses a pole in 6 seconds. What is its speed?","20 m/s","15 m/s","25 m/s","18 m/s",0,"Speed = 120/6 = 20 m/s.","Beginner"),
                    new Q("If 20% of a number is 50, what is the number?","200","250","300","150",1,"Number = 50/0.20 = 250.","Beginner"),
                    new Q("A can complete a job in 12 days and B in 18 days. How long together?","7.2 days","8 days","6 days","9 days",0,"Combined rate = 1/12+1/18=5/36, so time=36/5=7.2 days.","Intermediate"),
                    new Q("The average of 8 numbers is 15. If one number 22 is removed, what is the new average?","13","14","14.0?","15",1,"Total=120; remaining=98; average=98/7=14.","Beginner"),
                    new Q("A shopkeeper gives 10% discount on a marked price of 800. What is the selling price?","700","720","740","760",1,"Selling price = 800×0.90 = 720.","Beginner"),
                    new Q("If CP is 500 and SP is 575, what is the profit percentage?","10%","12%","15%","20%",2,"Profit=75; 75/500×100=15%.","Beginner"),
                    new Q("A sum becomes 1200 at 10% simple interest in 2 years. What was the principal?","1000","1100","900","1050",0,"1200=P(1+0.10×2)=1.2P, so P=1000.","Intermediate"),
                    new Q("What is the probability of getting an even number on a fair six-sided die?","1/3","1/2","2/3","1/6",1,"Even outcomes are 2,4,6: 3/6=1/2.","Beginner"),
                    new Q("If x:y = 3:5 and y:z = 10:7, then x:z is?","3:7","6:7","5:7","6:5",1,"Make y=10: x=6 and z=7, so 6:7.","Intermediate"),
                    new Q("A number is increased by 20% and then decreased by 20%. Net change is?","0%","4% decrease","4% increase","2% decrease",1,"1.2×0.8=0.96, a 4% decrease.","Beginner"),
                    new Q("Find the next number: 2, 6, 12, 20, 30, ?","40","42","44","48",1,"Differences are 4,6,8,10, so next is 42.","Beginner"),
                    new Q("If 5 machines make 500 units in 4 hours, how many units do 10 machines make in 4 hours at the same rate?","750","1000","1250","1500",1,"Doubling machines doubles output: 1000 units.","Beginner"),
                    new Q("A boat travels 30 km downstream in 2 hours. If stream speed is 3 km/h, what is boat speed in still water?","12 km/h","15 km/h","18 km/h","10 km/h",0,"Downstream speed=15; still-water speed=15-3=12 km/h.","Intermediate"),
                    new Q("A man walks at 5 km/h. How long does he take to cover 2.5 km?","20 min","30 min","40 min","50 min",1,"Time=2.5/5 hour=0.5 hour=30 minutes.","Beginner"),
                    new Q("If 3x - 7 = 20, x equals?","7","9","11","13",1,"3x=27, so x=9.","Beginner"),
                    new Q("In a class, 60% are boys. If there are 24 girls, what is the total number of students?","40","50","60","36",2,"Girls are 40%, so total = 24/0.40 = 60.","Beginner"),
                    new Q("If a clock shows 3:00, what is the angle between the hands?","60°","90°","120°","180°",1,"At 3:00 the hands are perpendicular: 90°.","Beginner"),
                    new Q("A person buys an item for 800 and sells it for 680. Loss percentage is?","10%","12%","15%","20%",2,"Loss=120; 120/800×100=15%.","Beginner"),
                    new Q("If all engineers are graduates and some graduates are managers, which conclusion is definitely true?","All managers are engineers","Some engineers are managers","All engineers are graduates","No manager is a graduate",2,"The first statement directly implies all engineers are graduates.","Intermediate"),
                    new Q("Choose the odd one out: 8, 27, 64, 100, 125","8","27","100","125",2,"8,27,64,125 are cubes; 100 is not.","Beginner")
            );
            default -> List.of();
        };
    }
}