package com.aitutor.controller;
import com.aitutor.security.JwtService; import com.aitutor.config.AuditLog; import com.aitutor.config.AuditLogRepository; import com.aitutor.service.AuthService; import com.aitutor.entity.User; import jakarta.validation.constraints.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/auth") public class AuthController { private final AuthService auth; private final JwtService jwt; private final AuditLogRepository audit; public AuthController(AuthService a,JwtService j,AuditLogRepository audit){auth=a;jwt=j;this.audit=audit;}
 record Req(@NotBlank String name,@NotBlank @Email String email,@Size(min=6) String password){} record Login(@NotBlank @Email String email,@NotBlank String password){} record Res(String token,Long id,String name,String email,String role,boolean profileComplete){}
 @PostMapping("/register") Res register(@jakarta.validation.Valid @RequestBody Req r){User u=auth.register(r.name(),r.email(),r.password());return new Res(jwt.token(u.getEmail()),u.getId(),u.getName(),u.getEmail(),u.getRole(),profileComplete(u));}
 @PostMapping("/login") Res login(@jakarta.validation.Valid @RequestBody Login r){User u=auth.find(r.email()); if(u.isBlocked()||!u.isActive()) throw new IllegalArgumentException("Account is inactive or blocked"); if(!auth.matchesPassword(r.password(), u.getPassword())) throw new IllegalArgumentException("Invalid credentials"); u=auth.syncOwnerRole(u); if("ADMIN".equalsIgnoreCase(u.getRole())) audit.save(new AuditLog(u.getEmail(),"ADMIN_LOGIN","auth","SUCCESS",null)); return new Res(jwt.token(u.getEmail()),u.getId(),u.getName(),u.getEmail(),u.getRole(),profileComplete(u));}
 @GetMapping("/me") Res me(@RequestHeader(value="Authorization",required=false) String authorization){ if(authorization==null||!authorization.startsWith("Bearer ")) throw new IllegalArgumentException("Not signed in"); User u=auth.find(jwt.email(authorization.substring(7))); if(u.isBlocked()||!u.isActive()) throw new IllegalArgumentException("Account is inactive or blocked"); u=auth.syncOwnerRole(u); return new Res(jwt.token(u.getEmail()),u.getId(),u.getName(),u.getEmail(),u.getRole(),profileComplete(u));}

 private boolean profileComplete(User u){ return u.getLearningGoal()!=null && !u.getLearningGoal().isBlank() && u.getInterests()!=null && !u.getInterests().isBlank() && u.getWeaknesses()!=null && !u.getWeaknesses().isBlank() && u.getLearningStyle()!=null && !u.getLearningStyle().isBlank(); }
}
