import React,{useEffect,useMemo,useState} from 'react';
import {Icon as NovaIcon,BookOpen,BarChart3,FileText,BrainCircuit,Target,RefreshCw,Plus,Trash2,UploadCloud,CheckCircle2} from './icons.jsx';
const ArrowLeft=p=><NovaIcon name="ChevronLeft" {...p}/>; const Users=p=><NovaIcon name="UserRound" {...p}/>; const ShieldCheck=p=><NovaIcon name="CheckCircle2" {...p}/>; const Bell=p=><NovaIcon name="MessageCircle" {...p}/>; const SettingsIcon=p=><NovaIcon name="Settings" {...p}/>; const Activity=p=><NovaIcon name="BarChart3" {...p}/>; const Database=p=><NovaIcon name="BookOpen" {...p}/>; const Search=p=><NovaIcon name="FileSearch" {...p}/>; const LockKeyhole=p=><NovaIcon name="WandSparkles" {...p}/>; const XCircle=p=><NovaIcon name="StopCircle" {...p}/>; const Community=p=><NovaIcon name="MessageCircle" {...p}/>;

export default function AdminControlCenter({user,courses,refreshCourses,api,onBack}){
 const [tab,setTab]=useState('dashboard');
 const [loading,setLoading]=useState(true),[error,setError]=useState('');
 const [dash,setDash]=useState(null),[users,setUsers]=useState([]),[questions,setQuestions]=useState([]),[audit,setAudit]=useState([]),[announcements,setAnnouncements]=useState([]),[settings,setSettings]=useState({}),[communityPosts,setCommunityPosts]=useState([]),[selectedCommunity,setSelectedCommunity]=useState([]);
 const [query,setQuery]=useState(''),[courseId,setCourseId]=useState(courses[0]?.id||'');
 const [courseForm,setCourseForm]=useState({title:'',description:'',level:'Beginner',icon:'✦'});
 const [lessonForm,setLessonForm]=useState({title:'',topic:'',content:''});
 const [questionForm,setQuestionForm]=useState({courseId:courses[0]?.id||'',question:'',optionA:'',optionB:'',optionC:'',optionD:'',correctOption:0,explanation:'',difficulty:'Medium'});
 const [announcementForm,setAnnouncementForm]=useState({title:'',message:'',target:'ALL',published:true});
 const [gateSubject,setGateSubject]=useState('engineering-mathematics'),[gateFile,setGateFile]=useState(null),[gateNotes,setGateNotes]=useState([]);
 const [busy,setBusy]=useState('');
 const [aiStatus,setAiStatus]=useState(null),[health,setHealth]=useState(null),[knowledgeDocs,setKnowledgeDocs]=useState([]),[knowledgeFile,setKnowledgeFile]=useState(null);
 const [settingDraft,setSettingDraft]=useState({});
 const nav=[['dashboard','Dashboard',BarChart3],['users','Users',Users],['courses','Courses',BookOpen],['questions','Question Bank',Target],['quizzes','Quizzes & Tests',Target],['ai','AI Control',BrainCircuit],['analytics','Analytics',Activity],['announcements','Announcements',Bell],['security','Security & Audit',ShieldCheck],['settings','Platform Settings',SettingsIcon],['health','System Health',Database],['gate','GATE PDFs',FileText],['knowledge','Knowledge PDFs',FileText],['community','Community Feed',Community]];
 const loadAnnouncements=async()=>{try{const [n,a]=await Promise.all([api('/admin/announcements'),api('/admin/audit-logs')]);setAnnouncements(n||[]);setAudit(a||[])}catch(e){setError(e.message||'Announcement data could not load.')}};
 const loadAll=async()=>{setLoading(true);setError('');try{const [d,u,q,a,n,s,h,ai,g,nk,cp]=await Promise.all([api('/admin/dashboard'),api('/admin/users'),api('/admin/questions'),api('/admin/audit-logs'),api('/admin/announcements'),api('/admin/settings'),api('/health'),api('/ai/status'),api('/admin/gate-notes'),api('/knowledge'),api('/admin/community/posts')]);setDash(d);setUsers(u||[]);setQuestions(q||[]);setAudit(a||[]);setAnnouncements(n||[]);setSettings(s||{});setSettingDraft(s||{});setHealth(h);setAiStatus(ai);setGateNotes(g||[]);setKnowledgeDocs(nk||[]);setCommunityPosts(Array.isArray(cp)?cp:[]);setSelectedCommunity([])}catch(e){setError(e.message||'Admin data could not load.')}finally{setLoading(false)}};
 useEffect(()=>{loadAll()},[]);
 useEffect(()=>{if(!courseId&&courses[0])setCourseId(courses[0].id);if(!questionForm.courseId&&courses[0])setQuestionForm(x=>({...x,courseId:courses[0].id}))},[courses]);
 const filteredUsers=useMemo(()=>users.filter(u=>!query.trim()||`${u.name} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
 const filteredQuestions=useMemo(()=>questions.filter(q=>!query.trim()||`${q.question} ${q.course} ${q.difficulty}`.toLowerCase().includes(query.toLowerCase())),[questions,query]);
 async function act(key,fn){setBusy(key);try{await fn();await loadAll();refreshCourses?.()}catch(e){setError(e.message||'Action failed.')}finally{setBusy('')}}
 async function createCourse(){if(!courseForm.title.trim())return;await act('course-create',async()=>{await api('/admin/courses',{method:'POST',body:JSON.stringify(courseForm)});setCourseForm({title:'',description:'',level:'Beginner',icon:'✦'})})}
 async function deleteCourse(c){if(!confirm(`Delete “${c.title}” and its lessons/questions/progress?`))return;await act('course-'+c.id,()=>api(`/admin/courses/${c.id}`,{method:'DELETE'}))}
 async function publishCourse(c){await act('publish-'+c.id,()=>api(`/admin/courses/${c.id}/publish?published=${!c.published}`,{method:'PATCH'}))}
 async function addLesson(){if(!courseId||!lessonForm.title.trim())return;await act('lesson-create',async()=>{await api(`/admin/courses/${courseId}/lessons`,{method:'POST',body:JSON.stringify(lessonForm)});setLessonForm({title:'',topic:'',content:''})})}
 async function saveQuestion(){if(!questionForm.courseId||!questionForm.question.trim())return;await act('question-save',async()=>{await api('/admin/questions',{method:'POST',body:JSON.stringify({...questionForm,correctOption:Number(questionForm.correctOption)})});setQuestionForm(x=>({...x,question:'',optionA:'',optionB:'',optionC:'',optionD:'',explanation:''}))})}
 async function deleteQuestion(q){if(!confirm('Delete this question?'))return;await act('question-'+q.id,()=>api(`/admin/questions/${q.id}`,{method:'DELETE'}))}
 async function toggleUser(u,kind){await act('user-'+u.id+'-'+kind,()=>api(`/admin/users/${u.id}/status`,{method:'PATCH',body:JSON.stringify(kind==='block'?{blocked:!u.blocked}:{active:!u.active})}))}
 async function changeRole(u){const role=prompt('Enter role: STUDENT or ADMIN',u.role);if(!role)return;await act('role-'+u.id,()=>api(`/admin/users/${u.id}/role`,{method:'PATCH',body:JSON.stringify({role})}))}
 async function createAnnouncement(){if(!announcementForm.title.trim()||!announcementForm.message.trim())return;setBusy('announcement-create');try{await api('/admin/announcements',{method:'POST',body:JSON.stringify(announcementForm)});setAnnouncementForm({title:'',message:'',target:'ALL',published:true});await loadAnnouncements();refreshCourses?.()}catch(e){setError(e.message||'Announcement could not be created.')}finally{setBusy('')};}
 async function deleteAnnouncement(id){if(!confirm('Delete this announcement?'))return;setBusy('announcement-'+id);try{await api(`/admin/announcements/${id}`,{method:'DELETE'});setAnnouncements(prev=>prev.filter(a=>a.id!==id));const auditRows=await api('/admin/audit-logs');setAudit(auditRows||[])}catch(e){setError(e.message||'Announcement could not be deleted.')}finally{setBusy('')}}
 async function deleteCommunityPost(id){if(!confirm('Delete this community post?'))return;await act('community-post-'+id,()=>api(`/admin/community/posts/${id}`,{method:'DELETE'}))}
 async function clearCommunityFeed(){if(!communityPosts.length)return;if(!confirm(`Clear the entire community feed? This will permanently delete all ${communityPosts.length===100?'currently stored/loaded and any additional':'available'} community posts.`))return;await act('community-clear',async()=>{await api('/admin/community/posts',{method:'DELETE'});setSelectedCommunity([])})}
 async function deleteSelectedCommunity(){if(!selectedCommunity.length)return;if(!confirm(`Delete ${selectedCommunity.length} selected community post${selectedCommunity.length===1?'':'s'}?`))return;await act('community-selected',async()=>{for(const id of selectedCommunity) await api(`/admin/community/posts/${id}`,{method:'DELETE'});setSelectedCommunity([])})}
 async function saveSettings(){await act('settings',()=>api('/admin/settings',{method:'PUT',body:JSON.stringify(settingDraft)}))}
 async function uploadKnowledge(){if(!knowledgeFile)return;await act('knowledge-upload',async()=>{const f=new FormData();f.append('file',knowledgeFile);await api('/knowledge/upload',{method:'POST',body:f});setKnowledgeFile(null)})}
 async function deleteKnowledge(d){if(!confirm(`Delete indexed PDF “${d.fileName}”?`))return;await act('knowledge-'+d.id,()=>api(`/knowledge/${d.id}`,{method:'DELETE'}))}
 async function uploadGate(){if(!gateFile)return;await act('gate-upload',async()=>{const f=new FormData();f.append('subject',gateSubject);f.append('file',gateFile);await api('/admin/gate-notes',{method:'POST',body:f});setGateFile(null);})}
 async function deleteGate(n){if(!confirm(`Remove ${n.filename}?`))return;await act('gate-'+n.filename,()=>api(`/admin/gate-notes/${encodeURIComponent(n.filename)}`,{method:'DELETE'}))}
 if(loading)return <div className="admin-center-state"><RefreshCw className="spin" size={28}/><h2>Loading Control Center…</h2><p>Verifying admin access and loading live platform data.</p></div>;
 if(error)return <div className="admin-center-state"><XCircle size={34}/><h2>Admin workspace unavailable</h2><p>{error}</p><button className="primary" onClick={loadAll}><RefreshCw size={15}/> Retry</button></div>;
 const Stat=({label,value,icon})=><div className="ac-stat"><div className="ac-stat-icon">{icon}</div><div><strong>{value}</strong><span>{label}</span></div></div>;
 return <div className="admin-center">
  <div className="ac-head"><div className="ac-head-left"><button className="ac-back" onClick={onBack} title="Back to NovaTutor"><ArrowLeft size={16}/> <span>Back to app</span></button><div><span className="eyebrow">OWNER • PRODUCTION CONTROL CENTER</span><h1>NovaTutor <span>Admin.</span></h1><p>Secure platform operations, content, AI, analytics and audit controls.</p></div></div><button className="icon-btn" onClick={loadAll} title="Refresh live data"><RefreshCw size={18}/></button></div>
  <div className="ac-nav">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setQuery('')}}><I size={15}/>{label}</button>)}</div>
  {tab==='dashboard'&&<><div className="ac-stats"><Stat label="Total users" value={dash?.users??0} icon={<Users size={19}/>}/><Stat label="Active users" value={dash?.activeUsers??0} icon={<CheckCircle2 size={19}/>}/><Stat label="Courses" value={dash?.courses??0} icon={<BookOpen size={19}/>}/><Stat label="Published courses" value={dash?.publishedCourses??0} icon={<BookOpen size={19}/>}/><Stat label="Lessons" value={dash?.lessons??0} icon={<FileText size={19}/>}/><Stat label="Questions" value={dash?.questions??0} icon={<Target size={19}/>}/><Stat label="Quiz attempts" value={dash?.attempts??0} icon={<BarChart3 size={19}/>}/><Stat label="Audit events" value={dash?.auditEvents??0} icon={<ShieldCheck size={19}/>}/></div><div className="ac-grid"><section className="ac-panel"><PanelTitle title="Operational snapshot" sub="Live backend-backed counts"/><div className="ac-health-list"><div><span>Backend</span><b className="ok">Operational</b></div><div><span>Database</span><b className="ok">Connected</b></div><div><span>AI provider</span><b className={aiStatus?.configured?'ok':'warn'}>{aiStatus?.configured?'Configured':'Configuration required'}</b></div><div><span>Current admin</span><b>{user?.email}</b></div></div></section><section className="ac-panel"><PanelTitle title="Recent admin activity" sub="Latest 6 audit events"/><div className="ac-activity">{audit.slice(0,6).map(x=><div key={x.id}><b>{x.action}</b><span>{x.target||'Platform'} • {new Date(x.createdAt).toLocaleString()}</span></div>)}{!audit.length&&<Empty text="No admin activity recorded yet."/>}</div></section></div></>}
  {tab==='users'&&<section className="ac-panel"><Toolbar title="User Management" sub="Search, secure status controls and role administration." query={query} setQuery={setQuery} refresh={loadAll}/><div className="ac-table">{filteredUsers.map(u=><div className="ac-row" key={u.id}><div className="ac-avatar">{u.name?.[0]?.toUpperCase()||'U'}</div><div><b>{u.name}</b><span>{u.email}</span></div><span className={'ac-pill '+(u.role==='ADMIN'?'purple':'')}>{u.role}</span><span className={'ac-pill '+(u.blocked?'red':u.active?'green':'amber')}>{u.blocked?'BLOCKED':u.active?'ACTIVE':'INACTIVE'}</span><div className="ac-actions">{u.role!=='ADMIN'&&<><button className="secondary compact" onClick={()=>toggleUser(u,'block')}>{u.blocked?'Unblock':'Block'}</button><button className="secondary compact" onClick={()=>toggleUser(u,'active')}>{u.active?'Deactivate':'Activate'}</button><button className="secondary compact" onClick={()=>changeRole(u)}>Role</button></>}</div></div>)}{!filteredUsers.length&&<Empty text="No matching users."/>}</div></section>}
  {tab==='courses'&&<><div className="ac-grid"><section className="ac-panel"><PanelTitle title="Course Management" sub="Create, publish and safely remove curriculum."/><div className="ac-form-grid"><input placeholder="Course title" value={courseForm.title} onChange={e=>setCourseForm({...courseForm,title:e.target.value})}/><input placeholder="Icon" value={courseForm.icon} onChange={e=>setCourseForm({...courseForm,icon:e.target.value})}/><select value={courseForm.level} onChange={e=>setCourseForm({...courseForm,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><textarea placeholder="Course description" value={courseForm.description} onChange={e=>setCourseForm({...courseForm,description:e.target.value})}/></div><button className="primary" disabled={busy==='course-create'} onClick={createCourse}><Plus size={15}/> Create course</button></section><section className="ac-panel"><PanelTitle title="Lecture Builder" sub="Group lessons by topic/category."/><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><input placeholder="Lecture title" value={lessonForm.title} onChange={e=>setLessonForm({...lessonForm,title:e.target.value})}/><input placeholder="Topic / category" value={lessonForm.topic} onChange={e=>setLessonForm({...lessonForm,topic:e.target.value})}/><textarea className="ac-content-area" placeholder="Detailed lecture content" value={lessonForm.content} onChange={e=>setLessonForm({...lessonForm,content:e.target.value})}/><button className="primary" disabled={!courseId||!lessonForm.title.trim()||busy==='lesson-create'} onClick={addLesson}><Plus size={15}/> Publish lecture</button></section></div><section className="ac-panel"><PanelTitle title="Course Library" sub="Publish/unpublish without destroying content."/><div className="ac-course-list">{courses.map(c=><div className="ac-course-row" key={c.id}><div className="ac-course-icon">{c.icon}</div><div><b>{c.title}</b><span>{c.level} • {c.totalLessons||0} lessons</span><small>{c.description||'No description'}</small></div><span className={'ac-pill '+(c.published!==false?'green':'amber')}>{c.published!==false?'PUBLISHED':'DRAFT'}</span><div className="ac-actions"><button className="secondary compact" onClick={()=>publishCourse(c)}>{c.published!==false?'Unpublish':'Publish'}</button><button className="danger-btn" onClick={()=>deleteCourse(c)} disabled={busy==='course-'+c.id}><Trash2 size={14}/> Delete</button></div></div>)}</div></section></>}
  {tab==='questions'&&<><div className="ac-grid"><section className="ac-panel"><PanelTitle title="Question Bank" sub="Create hard, explainable course questions."/><select value={questionForm.courseId} onChange={e=>setQuestionForm({...questionForm,courseId:e.target.value})}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><textarea placeholder="Question" value={questionForm.question} onChange={e=>setQuestionForm({...questionForm,question:e.target.value})}/><input placeholder="Option A" value={questionForm.optionA} onChange={e=>setQuestionForm({...questionForm,optionA:e.target.value})}/><input placeholder="Option B" value={questionForm.optionB} onChange={e=>setQuestionForm({...questionForm,optionB:e.target.value})}/><input placeholder="Option C" value={questionForm.optionC} onChange={e=>setQuestionForm({...questionForm,optionC:e.target.value})}/><input placeholder="Option D" value={questionForm.optionD} onChange={e=>setQuestionForm({...questionForm,optionD:e.target.value})}/><div className="ac-two"><select value={questionForm.correctOption} onChange={e=>setQuestionForm({...questionForm,correctOption:e.target.value})}><option value="0">Correct: A</option><option value="1">Correct: B</option><option value="2">Correct: C</option><option value="3">Correct: D</option></select><select value={questionForm.difficulty} onChange={e=>setQuestionForm({...questionForm,difficulty:e.target.value})}><option>Easy</option><option>Medium</option><option>Hard</option></select></div><textarea placeholder="Explanation" value={questionForm.explanation} onChange={e=>setQuestionForm({...questionForm,explanation:e.target.value})}/><button className="primary" onClick={saveQuestion} disabled={busy==='question-save'}><Plus size={15}/> Add question</button></section><section className="ac-panel"><Toolbar title="Question Library" sub={`${questions.length} stored questions`} query={query} setQuery={setQuery} refresh={loadAll}/><div className="ac-question-list">{filteredQuestions.slice(0,100).map(q=><div className="ac-question-row" key={q.id}><div><span className="ac-pill">{q.difficulty||'Unrated'}</span><b>{q.question}</b><small>{q.course} • Correct option {String.fromCharCode(65+(q.correctOption||0))}</small></div><button className="danger-btn" onClick={()=>deleteQuestion(q)}><Trash2 size={14}/></button></div>)}{!filteredQuestions.length&&<Empty text="No questions found."/>}</div></section></div></>}
  {tab==='quizzes'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="Quiz & Test Management" sub="Manage the question pools that power NovaTutor quizzes and tests."/><div className="ac-health-list"><div><span>Total question pool</span><b>{questions.length}</b></div><div><span>Total quiz attempts</span><b>{dash?.attempts??0}</b></div><div><span>Available courses</span><b>{courses.length}</b></div><div><span>Assessment engine</span><b className="ok">Operational</b></div></div><button className="primary" onClick={()=>setTab('questions')}><Target size={15}/> Manage question bank</button></section><section className="ac-panel"><PanelTitle title="Quiz Coverage" sub="Question distribution by course."/><div className="ac-course-list">{courses.map(c=>{const count=questions.filter(q=>String(q.courseId)===String(c.id)||q.course===c.title).length;return <div className="ac-course-row" key={c.id}><div className="ac-course-icon">{c.icon}</div><div><b>{c.title}</b><span>{count} question{count===1?'':'s'} in quiz pool</span></div><span className={'ac-pill '+(count?'green':'amber')}>{count?'READY':'EMPTY'}</span><div className="ac-actions"><button className="secondary compact" onClick={()=>{setQuestionForm(x=>({...x,courseId:c.id}));setTab('questions')}}>Manage</button></div></div>})}{!courses.length&&<Empty text="No courses available."/>}</div></section></div>}
  {tab==='ai'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="AI Control Center" sub="Safe status and operational controls."/><div className="ac-control"><div><b>AI Provider</b><span>{aiStatus?.model||'Unknown model'}</span></div><span className={'ac-pill '+(aiStatus?.configured?'green':'red')}>{aiStatus?.configured?'READY':'NOT CONFIGURED'}</span></div><div className="ac-control"><div><b>API secret exposure</b><span>Keys remain server-side and are never displayed.</span></div><LockKeyhole size={18}/></div><div className="ac-control"><div><b>Existing AI integration</b><span>Preserved; admin panel does not replace provider wiring.</span></div><CheckCircle2 className="ok" size={18}/></div></section><section className="ac-panel"><PanelTitle title="AI Usage Guardrails" sub="Operational policy controls stored without secrets."/><label className="ac-setting"><span>AI enabled</span><input type="checkbox" checked={settingDraft['ai.enabled']!=='false'} onChange={e=>setSettingDraft({...settingDraft,'ai.enabled':String(e.target.checked)})}/></label><label className="ac-setting"><span>AI request limit / user / day</span><input value={settingDraft['ai.dailyLimit']||'100'} onChange={e=>setSettingDraft({...settingDraft,'ai.dailyLimit':e.target.value})}/></label><button className="primary" onClick={saveSettings}><SettingsIcon size={15}/> Save AI controls</button></section></div>}
  {tab==='analytics'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="Analytics Overview" sub="Live counts from existing persistence."/><div className="analytics-bars"><Bar label="Users" value={dash?.users||0} max={Math.max(1,dash?.users||1)}/><Bar label="Active users" value={dash?.activeUsers||0} max={Math.max(1,dash?.users||1)}/><Bar label="Courses" value={dash?.courses||0} max={Math.max(1,dash?.courses||1)}/><Bar label="Lessons" value={dash?.lessons||0} max={Math.max(1,dash?.lessons||1)}/><Bar label="Quiz attempts" value={dash?.attempts||0} max={Math.max(1,dash?.attempts||1)}/></div></section><section className="ac-panel"><PanelTitle title="Platform Signals" sub="Operational indicators."/><div className="ac-health-list"><div><span>Blocked accounts</span><b>{dash?.blockedUsers||0}</b></div><div><span>Questions</span><b>{dash?.questions||0}</b></div><div><span>Audit events</span><b>{dash?.auditEvents||0}</b></div><div><span>AI</span><b className={aiStatus?.configured?'ok':'warn'}>{aiStatus?.configured?'Healthy':'Needs configuration'}</b></div></div></section></div>}
  {tab==='announcements'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="Create Announcement" sub="Publish platform notices without external messaging."/><input placeholder="Title" value={announcementForm.title} onChange={e=>setAnnouncementForm({...announcementForm,title:e.target.value})}/><textarea className="ac-content-area" placeholder="Message" value={announcementForm.message} onChange={e=>setAnnouncementForm({...announcementForm,message:e.target.value})}/><div className="ac-two"><select value={announcementForm.target} onChange={e=>setAnnouncementForm({...announcementForm,target:e.target.value})}><option>ALL</option><option>STUDENTS</option></select><label className="ac-check"><input type="checkbox" checked={announcementForm.published} onChange={e=>setAnnouncementForm({...announcementForm,published:e.target.checked})}/> Published</label></div><button className="primary" onClick={createAnnouncement}><Bell size={15}/> Publish announcement</button></section><section className="ac-panel"><PanelTitle title="Announcement History" sub="Recent platform announcements."/><div className="ac-announcements">{announcements.map(a=><div key={a.id}><div><b>{a.title}</b><span>{a.target} • {a.published?'Published':'Draft'} • {new Date(a.createdAt).toLocaleString()}</span></div><button className="danger-btn" onClick={()=>deleteAnnouncement(a.id)}><Trash2 size={14}/></button><p>{a.message}</p></div>)}{!announcements.length&&<Empty text="No announcements yet."/>}</div></section></div>}
  {tab==='security'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="Security Center" sub="Server-side authorization and account protection."/><div className="ac-security-checks"><Check text="Admin APIs verify JWT + ADMIN role server-side."/><Check text="Secrets are excluded from admin responses."/><Check text="Destructive course/user operations require protected endpoints."/><Check text="File upload accepts PDF only and sanitizes filenames."/><Check text="Audit events capture important admin mutations."/></div></section><section className="ac-panel"><PanelTitle title="Audit Log" sub="Latest 200 events."/><div className="ac-audit">{audit.map(x=><div key={x.id}><b>{x.action}</b><span>{x.adminEmail} • {x.target||'—'} • {x.status}</span><small>{new Date(x.createdAt).toLocaleString()}</small></div>)}{!audit.length&&<Empty text="No audit events yet."/>}</div></section></div>}
  {tab==='settings'&&<section className="ac-panel"><PanelTitle title="Platform Settings" sub="Only non-secret configuration can be stored here."/><div className="ac-setting-grid">{Object.entries(settingDraft).filter(([k])=>!/(secret|password|token|apikey|api-key)/i.test(k)).map(([k,v])=><label key={k}><span>{k}</span><input value={v} onChange={e=>setSettingDraft({...settingDraft,[k]:e.target.value})}/></label>)}<label><span>platform.name</span><input value={settingDraft['platform.name']||'NovaTutor'} onChange={e=>setSettingDraft({...settingDraft,'platform.name':e.target.value})}/></label><label><span>maintenance.mode</span><select value={settingDraft['maintenance.mode']||'false'} onChange={e=>setSettingDraft({...settingDraft,'maintenance.mode':e.target.value})}><option>false</option><option>true</option></select></label></div><button className="primary" onClick={saveSettings}><SettingsIcon size={15}/> Save settings</button><div className="ac-secret-note"><LockKeyhole size={16}/><span>JWT secrets, database passwords, Gemini keys and other credentials remain environment/server-side only.</span></div></section>}
  {tab==='community'&&<div className="ac-grid"><section className="ac-panel ac-community-panel"><PanelTitle title="Community Feed" sub="Moderate student Ask to Community discussions."/><div className="ac-community-actions"><label className="ac-check"><input type="checkbox" checked={communityPosts.length>0&&selectedCommunity.length===communityPosts.length} onChange={e=>setSelectedCommunity(e.target.checked?communityPosts.map(p=>p.id):[])}/> Select all loaded posts</label><div className="ac-inline-actions"><button className="secondary" disabled={!selectedCommunity.length||!!busy} onClick={deleteSelectedCommunity}><Trash2 size={14}/> Delete selected</button><button className="danger-btn ac-clear-community" disabled={!communityPosts.length||!!busy} onClick={clearCommunityFeed}><Trash2 size={14}/> Clear entire feed</button></div></div><div className="ac-community-list">{communityPosts.map(p=><article className="ac-community-item" key={p.id}><label className="ac-community-check"><input type="checkbox" checked={selectedCommunity.includes(p.id)} onChange={e=>setSelectedCommunity(prev=>e.target.checked?[...new Set([...prev,p.id])]:prev.filter(id=>id!==p.id))}/></label><div className="ac-community-copy"><div><b>{p.author||'Student'}</b><span>{p.createdAt?new Date(p.createdAt).toLocaleString():'Recently'}</span></div><p>{p.text}</p></div><button className="danger-btn" disabled={!!busy} onClick={()=>deleteCommunityPost(p.id)} title="Delete post"><Trash2 size={14}/></button></article>)}{!communityPosts.length&&<Empty text="No community posts to moderate."/>}</div></section><aside className="ac-panel"><PanelTitle title="Moderation" sub="Admin actions are permanent."/><div className="ac-security-checks"><Check text="Delete individual posts without affecting other discussions."/><Check text="Delete selected posts in one action."/><Check text="Clear the complete community feed in one action."/><Check text="Every moderation action is recorded in the audit log."/></div></aside></div>}
  {tab==='health'&&<div className="ac-grid"><section className="ac-panel"><PanelTitle title="System Health" sub="Safe operational information only."/><div className="ac-health-list"><div><span>Backend API</span><b className="ok">{health?.status||'UP'}</b></div><div><span>Application</span><b>{health?.app||'NovaTutor'}</b></div><div><span>AI provider</span><b className={aiStatus?.configured?'ok':'warn'}>{aiStatus?.configured?'Configured':'Not configured'}</b></div><div><span>Environment</span><b>Application server</b></div></div></section><section className="ac-panel"><PanelTitle title="Production checklist" sub="Safe deployment indicators."/><div className="ac-security-checks"><Check text="No secret values are rendered in Admin UI."/><Check text="Admin routes are protected server-side."/><Check text="Large lists are capped/paginated at API boundaries where applicable."/><Check text="User-friendly error states are available in the Admin workspace."/></div></section></div>}
  {tab==='knowledge'&&<section className="ac-panel"><PanelTitle title="Knowledge Hub PDFs" sub="Admin-only upload and removal of indexed study material."/><div className="ac-two"><input type="file" accept="application/pdf,.pdf" onChange={e=>setKnowledgeFile(e.target.files?.[0]||null)}/><button className="primary" disabled={!knowledgeFile||busy==='knowledge-upload'} onClick={uploadKnowledge}><UploadCloud size={15}/> Upload & Index PDF</button></div><div className="ac-pdf-list">{knowledgeDocs.map(d=><div key={d.id}><div><b>{d.fileName}</b><span>{d.contentType||'PDF'} • {d.sizeBytes?Math.max(1,Math.round(d.sizeBytes/1024))+' KB':''}</span></div><div className="ac-actions"><a className="secondary compact" href={`/api/knowledge/${d.id}/chunks`} target="_blank" rel="noreferrer">Inspect</a><button className="danger-btn" onClick={()=>deleteKnowledge(d)}><Trash2 size={14}/> Remove</button></div></div>)}{!knowledgeDocs.length&&<Empty text="No indexed Knowledge Hub PDFs."/>}</div></section>}
  {tab==='gate'&&<section className="ac-panel"><PanelTitle title="GATE CSE PDF Library" sub="Admin-only multi-PDF management by subject."/><div className="ac-two"><select value={gateSubject} onChange={e=>setGateSubject(e.target.value)}><option value="engineering-mathematics">Engineering Mathematics</option><option value="digital-logic">Digital Logic</option><option value="computer-organization-architecture">COA</option><option value="programming-data-structures">Programming & Data Structures</option><option value="algorithms">Algorithms</option><option value="theory-of-computation">Theory of Computation</option><option value="compiler-design">Compiler Design</option><option value="operating-systems">Operating Systems</option><option value="databases">Databases</option><option value="computer-networks">Computer Networks</option><option value="general-aptitude">General Aptitude</option></select><input type="file" accept="application/pdf,.pdf" onChange={e=>setGateFile(e.target.files?.[0]||null)}/></div><button className="primary" disabled={!gateFile||busy==='gate-upload'} onClick={uploadGate}><UploadCloud size={15}/> Add PDF</button><div className="ac-pdf-list">{gateNotes.map(n=><div key={n.filename}><div><b>{n.subject}</b><span>{n.filename}</span></div><div className="ac-actions"><a className="secondary compact" href={n.url} target="_blank" rel="noreferrer">Open</a><button className="danger-btn" onClick={()=>deleteGate(n)}><Trash2 size={14}/> Remove</button></div></div>)}{!gateNotes.length&&<Empty text="No uploaded GATE PDFs."/>}</div></section>}
 </div>
}
function PanelTitle({title,sub}){return <div className="ac-panel-title"><div><span className="eyebrow">ADMIN MODULE</span><h2>{title}</h2><p>{sub}</p></div></div>}
function Toolbar({title,sub,query,setQuery,refresh}){return <div className="ac-toolbar"><div><h2>{title}</h2><p>{sub}</p></div><div className="ac-toolbar-tools"><div className="ac-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search…"/></div><button className="icon-btn" onClick={refresh}><RefreshCw size={17}/></button></div></div>}
function Empty({text}){return <div className="ac-empty">{text}</div>}
function Check({text}){return <div className="ac-check-line"><CheckCircle2 size={16}/><span>{text}</span></div>}
function Bar({label,value,max}){return <div className="ac-bar"><div><span>{label}</span><b>{value}</b></div><div className="ac-bar-track"><i style={{width:`${Math.min(100,Math.round((value/max)*100))}%`}}/></div></div>}
